tools/word-repeater/wR.Web/ViewModels/ChangeConfigurationVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace wR.Web.ViewModels
{
    public class ChangeConfigurationVm
    {
        [Required]
        [DisplayName("Source Language")]
        public Guid SourceLanguageId { get; set; }

        [Required]
        [DisplayName("Destination Language")]
        public Guid DestinationLanguageId { get; set; }

        [Required]
        [DisplayName("Flip Mode")]
        public bool IsFlipModeOn { get; set; }

        public IEnumerable<SelectListItem> SourceLanguageSelection { get; set; }

        public IEnumerable<SelectListItem> DestinationLanguageSelection { get; set; }
    }
}

tools/word-repeater/wR.Web/ViewModels/GuessingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using wR.Core.Domain;

namespace wR.Web.ViewModels
{
    public class GuessingViewModel
    {
        [Required]
        public Guid TranslationRowGuid { get; set; }

        [Required]
        [DisplayName("Source")]
        public string SourceText { get; set; }

        [Required]
        [DisplayName("Translation")]
        public string TranslatedText { get; set; }

        [DisplayName("Translation")]
        public string CorrectlyTranslatedText { get; set; }

        public bool MarkedCorrect { get; set; }

        public IEnumerable<TranslationRow> AllRowTranslations { get; set; }

        public GuessingViewModel()
        {
            AllRowTranslations = new List<TranslationRow>();
        }
    }
}

tools/word-repeater/wR.Web/Controllers/ConfigurationController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using wR.DAL;
using wR.Web.ViewModels;

namespace wR.Web.Controllers
{
    [RoutePrefix("configuration")]
    public class ConfigurationController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ConfigurationController()
        {
            _context = new ApplicationDbContext();
        }

        [Route(""), HttpGet]
        public ActionResult Index()
        {
            var changeConfigurationVm = new ChangeConfigurationVm
            {
                SourceLanguageSelection = GetLanguageSelection(),
                SourceLanguageId = Guid.Parse(ConfigurationManager.AppSettings["SourceLanguage"]),
                DestinationLanguageSelection = GetLanguageSelection(),
                DestinationLanguageId = Guid.Parse(ConfigurationManager.AppSettings["DestinationLanguage"]),
                IsFlipModeOn = bool.Parse(ConfigurationManager.AppSettings["FlipMode"])
            };
            return View(changeConfigurationVm);
        }

        [Route(""), HttpPost]
        public ActionResult Change(ChangeConfigurationVm changeViewModel)
        {
            ConfigurationManager.AppSettings["SourceLanguage"] = changeViewModel.SourceLanguageId.ToString();
            ConfigurationManager.AppSettings["DestinationLanguage"] = changeViewModel.DestinationLanguageId.ToString();
            ConfigurationManager.AppSettings["FlipMode"] = changeViewModel.IsFlipModeOn.ToString();

            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Fetches the list of available languages from the datastore
        /// </summary>
        /// <returns></returns>
        public IEnumerable<SelectListItem> GetLanguageSelection()
        {
            var languages = _context.Languages.Select(l => new SelectListItem
            {
                Value = l.Id.ToString(),
                Text = l.Code
            });

            return new SelectList(languages, "Value", "Text");
        }
    }
}

tools/word-repeater/wR.Web/Controllers/GuessingController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using wR.Core.Domain;
using wR.DAL;
using wR.Web.Services;
using wR.Web.ViewModels;

namespace wR.Web.Controllers
{
    [RoutePrefix("guessing")]
    public class GuessingController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly GuessingService _service;
        private readonly IDictionary<Guid, TranslationRow> _guessingSet;
        private readonly Guid _sourceLanguageGuid;
        private readonly Guid _targetLanguageGuid;

        public GuessingController()
        {
            _context = new ApplicationDbContext();
            _service = new GuessingService(_context);

            _guessingSet = _context.TranslationRows
                .Where(tr => tr.GuessAttempts.Count < 3)
                .ToDictionary(tr => tr.Id);

            _sourceLanguageGuid = Guid.Parse(ConfigurationManager.AppSettings["SourceLanguage"]);
            _targetLanguageGuid = Guid.Parse(ConfigurationManager.AppSettings["DestinationLanguage"]);
        }

        [Route(""), HttpGet]
        public async Task<ActionResult> Index()
        {
            var randomizer = new Random();
            var guessRow = _guessingSet.ElementAt(randomizer.Next(0,_guessingSet.Count-1)).Value;
            
            var sourceLanguage = await _context.Languages.SingleOrDefaultAsync(l => l.Id == _sourceLanguageGuid);
            
            var guessingVm = new GuessingViewModel
            {
                AllRowTranslations = await _service.GetTranslations(sourceLanguage?.Code, guessRow.GetTranslationByLanguageCode(sourceLanguage?.Code)),
                MarkedCorrect = false,
                SourceText = guessRow.GetTranslationByLanguageCode(sourceLanguage?.Code),
                TranslatedText = null,
                TranslationRowGuid = guessRow.Id
            };

            return View(guessingVm);
        }

        [Route("submit"), HttpPost]
        public async Task<ActionResult> SubmitGuess(string checkButton, string forceButton, GuessingViewModel indexVm)
        {
            if (!ModelState.IsValid)
            {
                return View("Index",indexVm);
            }

            if (checkButton != null)
            {
                indexVm.MarkedCorrect = false;
            }
            else
            {
                indexVm.MarkedCorrect = true;
            }

            var sourceLanguage = await _context.Languages.SingleOrDefaultAsync(l => l.Id == _sourceLanguageGuid);
            var targetLanguage = await _context.Languages.SingleOrDefaultAsync(l => l.Id == _targetLanguageGuid);

            foreach (var translation in indexVm.AllRowTranslations)
            {
                var correctTranslation = translation.GetTranslationByLanguageCode(targetLanguage.Code);
                indexVm.CorrectlyTranslatedText = correctTranslation;

                if (indexVm.TranslatedText == correctTranslation)
                {
                    var successfulGuess = new GuessAttempt();
                    _context.GuessAttempts.Add(successfulGuess.GetGuessAttempt(indexVm.SourceText,
                        indexVm.TranslatedText,
                        sourceLanguage,
                        targetLanguage,
                        translation.Id,
                        true,
                        indexVm.MarkedCorrect));
                    
                    await _context.SaveChangesAsync();

                    return RedirectToAction("Index");
                }
                else
                {
                    var failedGuess = new GuessAttempt();
                    _context.GuessAttempts.Add(failedGuess.GetGuessAttempt(indexVm.SourceText,
                        indexVm.TranslatedText,
                        sourceLanguage,
                        targetLanguage,
                        indexVm.TranslationRowGuid,
                        false,
                        indexVm.MarkedCorrect));

                    await _context.SaveChangesAsync();
                }
            }
            indexVm.TranslatedText = null;
            indexVm.MarkedCorrect = false;
            return View("Index", indexVm);
        }
    }
}

tools/word-repeater/wR.Web/Controllers/HomeController.cs
using System.Web.Mvc;
using wR.DAL;

namespace wR.Web.Controllers
{
    [RoutePrefix("")]
    public class HomeController : Controller
    {
        [Route("")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

tools/word-repeater/wR.Web/Controllers/TrainingController.cs
using System.Web.Mvc;
using wR.DAL;

namespace wR.Web.Controllers
{
    [RoutePrefix("training")]
    public class TrainingController : Controller
    {
        [Route("")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

tools/word-repeater/wR.Web/Views/Configuration/Index.cshtml
@model wR.Web.ViewModels.ChangeConfigurationVm
@{
    ViewBag.Title = "Configuration";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Change", "Configuration", FormMethod.Post, new {@class = "form-horizontal", @style = "height: 360px; margin-top:20px; padding-left: 30px; padding-right: 30px;" }))
{
    <fieldset>
        <div class="col-xs-4">
            <div class="form-group">
                @Html.LabelFor(m => m.SourceLanguageId)
                @Html.DropDownListFor(m => m.SourceLanguageId, Model.SourceLanguageSelection, new {@class = "form-control"})
                @Html.ValidationMessageFor(m => m.SourceLanguageId, null, new {@class = "label label-danger pull-right"})
                <br/>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.DestinationLanguageId)
                @Html.DropDownListFor(m => m.DestinationLanguageId, Model.DestinationLanguageSelection, new {@class = "form-control"})
                @Html.ValidationMessageFor(m => m.DestinationLanguageId, null, new {@class = "label label-danger pull-right"})
                <br/>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.IsFlipModeOn)
                @Html.CheckBoxFor(m => m.IsFlipModeOn)
                @Html.ValidationMessageFor(m => m.IsFlipModeOn, null, new {@class = "label label-danger pull-right"})
            </div>
        </div>
    </fieldset>

    <br />
    <div class="form-group pull-right">
        <input id="Save" type="submit" class="btn btn-primary pull-right" style="margin-left: 5px;" value="Save" />
    </div>
}

tools/word-repeater/wR.Web/Views/Guessing/Index.cshtml
@using wR.Web.Extensions
@model wR.Web.ViewModels.GuessingViewModel
@{
    ViewBag.Title = "Flipcard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.AntiForgeryToken()
<div class="row" style="margin-top: 20px;">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th scope="col">@Html.LabelFor(m => m.SourceText)</th>
                <th scope="col">@Html.LabelFor(m => m.CorrectlyTranslatedText)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">@Model.SourceText</th>
                <th scope="row">@Model.CorrectlyTranslatedText</th>
            </tr>
        </tbody>
    </table>
</div>

<br />
@using (Html.BeginForm("SubmitGuess", "Guessing", FormMethod.Post, new { @class = "form-inline", @style = "height: 360px; padding-left: 30px; padding-right: 30px;" }))
{
    @Html.HiddenForEnumerable(m => m.AllRowTranslations, h => h.Id, h => h.English, h => h.French, h => h.German, h => h.Italian, h => h.Polish, h => h.Spanish, h => h.Id)
    @Html.HiddenFor(m => m.TranslationRowGuid)
    @Html.HiddenFor(m => m.SourceText)
    <fieldset>
        <div class="col-xs-8">
            <div class="form-group" style="margin-left: 30px;">
                @Html.LabelFor(m => m.TranslatedText, new { @class = "label label-default" })
                @Html.TextBoxFor(m => m.TranslatedText, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.TranslatedText, null, new { @class = "label label-danger" })
            </div>
            <div class="form-group pull-right">
                <input type="submit" name="CheckButton" class="btn btn-primary pull-right" style="margin-left: 5px;" value="Submit Check"/>
                <input type="submit" name="ForceButton" class="btn btn-default" value="Force" />
            </div>
        </div>
    </fieldset>
    <br />
}

tools/word-repeater/wR.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Home</h2>

tools/word-repeater/wR.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("wR App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Training", "Index", "Training")</li>
                    <li>@Html.ActionLink("Configuration", "Index", "Configuration")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

tools/word-repeater/wR.Web/Views/Training/Index.cshtml
@{
    ViewBag.Title = "Training";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-xs-6 col-md-4">
    <div class="thumbnail tile tile-medium tile-blue">
        <a href="@Url.Action("Index", "Guessing")">
            <h1>
                Guess (?)
            </h1>
        </a>
    </div>
</div>